name: Periodic Health Check

on:
  schedule:
    - cron: "*/5 * * * *"  
  workflow_dispatch:  

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Perform Health Check
        uses: jtalk/url-health-check-action@v3
        with:
          url: "https://full-stack-open-pokedex-j0zf.onrender.com/health"
          max-attempts: 3
          retry-delay: 5s

      - name: Send success notification
        if: success()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "✅ Health check passed"

      - name: Send failure notification
        if: failure()
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        with:
          args: "❌ Health check failed!"
